### ISSUE TITLE
[Bug] Cannot find module error for libs that ng-doc uses

### ISSUE THREAD

**Issue by dhutaryan** [ng-doc/ng-doc#110]
### Is this a regression?

I don't know

### Description

Hello,
I've just installed `ng-doc` `v17.0.0` and couldn't run `ng serve`. I haven't user `ng-doc` before.
I used `ng add @ng-doc/add` and I had to fix some missing things by your manual guide.

### Please provide the exception or error you saw

```true
X [ERROR] TS2307: Cannot find module 'di-controls' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@ng-doc/app/type-controls/boolean-control/boolean-control.component.d.ts:2:26:
      2 │ import { DIControl } from 'di-controls';
        ╵                           ~~~~~~~~~~~~~


X [ERROR] TS2420: Class 'NgDocBooleanControlComponent' incorrectly implements interface 'NgDocTypeControl<boolean | undefined>'.
  Type 'NgDocBooleanControlComponent' is missing the following properties from type 'NgDocTypeControl<boolean | undefined>': writeValue, registerOnChange, registerOnTouched [plugin angular-compiler]

    node_modules/@ng-doc/app/type-controls/boolean-control/boolean-control.component.d.ts:4:21:
      4 │ export declare class NgDocBooleanControlComponent extends DIControl...
        ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~


X [ERROR] TS2307: Cannot find module 'di-controls' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@ng-doc/app/type-controls/number-control/number-control.component.d.ts:2:26:
      2 │ import { DIControl } from 'di-controls';
        ╵                           ~~~~~~~~~~~~~


X [ERROR] TS2420: Class 'NgDocNumberControlComponent' incorrectly implements interface 'NgDocTypeControl<number>'.
  Type 'NgDocNumberControlComponent' is missing the following properties from type 'NgDocTypeControl<number>': writeValue, registerOnChange, registerOnTouched [plugin angular-compiler]

    node_modules/@ng-doc/app/type-controls/number-control/number-control.component.d.ts:4:21:
      4 │ export declare class NgDocNumberControlComponent extends DIControl<...
        ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~


X [ERROR] TS2307: Cannot find module 'di-controls' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@ng-doc/app/type-controls/string-control/string-control.component.d.ts:2:26:
      2 │ import { DIControl } from 'di-controls';
        ╵                           ~~~~~~~~~~~~~


X [ERROR] TS2420: Class 'NgDocStringControlComponent' incorrectly implements interface 'NgDocTypeControl<string>'.
  Type 'NgDocStringControlComponent' is missing the following properties from type 'NgDocTypeControl<string>': registerOnChange, registerOnTouched [plugin angular-compiler]

    node_modules/@ng-doc/app/type-controls/string-control/string-control.component.d.ts:4:21:
      4 │ export declare class NgDocStringControlComponent extends DIControl<...
        ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~


X [ERROR] TS2307: Cannot find module 'di-controls' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@ng-doc/app/type-controls/type-alias-control/type-alias-control.component.d.ts:2:26:
      2 │ import { DIControl } from 'di-controls';
        ╵                           ~~~~~~~~~~~~~


X [ERROR] TS2420: Class 'NgDocTypeAliasControlComponent<T>' incorrectly implements interface 'NgDocTypeControl<T>'.
  Type 'NgDocTypeAliasControlComponent<T>' is missing the following properties from type 'NgDocTypeControl<T>': writeValue, registerOnChange, registerOnTouched [plugin angular-compiler]

    node_modules/@ng-doc/app/type-controls/type-alias-control/type-alias-control.component.d.ts:4:21:
      4 │ ...rt declare class NgDocTypeAliasControlComponent<T> extends DICon...
        ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


X [ERROR] TS2307: Cannot find module 'di-controls' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@ng-doc/ui-kit/cdk/combobox-host/combobox-host.component.d.ts:5:60:
      5 │ ...{ DICompareFunction, DICompareHost, DIControl } from 'di-controls';
        ╵                                                         ~~~~~~~~~~~~~


X [ERROR] TS2307: Cannot find module 'di-controls' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@ng-doc/ui-kit/classes/base-input/base-input.d.ts:2:26:
      2 │ import { DIControl } from 'di-controls';
        ╵                           ~~~~~~~~~~~~~


X [ERROR] TS2307: Cannot find module 'di-controls/controls/control' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@ng-doc/ui-kit/classes/base-input/base-input.d.ts:3:32:
      3 │ import { DIControlConfig } from 'di-controls/controls/control';
        ╵                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


X [ERROR] TS2307: Cannot find module 'di-controls' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@ng-doc/ui-kit/components/checkbox/checkbox.component.d.ts:2:31:
      2 │ import { DIStateControl } from 'di-controls';
        ╵                                ~~~~~~~~~~~~~


X [ERROR] TS2307: Cannot find module 'di-controls' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@ng-doc/ui-kit/components/clear-control/clear-control.component.d.ts:3:26:
      3 │ import { DIControl } from 'di-controls';
        ╵                           ~~~~~~~~~~~~~


X [ERROR] TS2307: Cannot find module 'di-controls' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@ng-doc/ui-kit/components/combobox/combobox.component.d.ts:5:26:
      5 │ import { DIControl } from 'di-controls';
        ╵                           ~~~~~~~~~~~~~


X [ERROR] TS2307: Cannot find module 'di-controls' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@ng-doc/ui-kit/components/option/option.component.d.ts:4:31:
      4 │ import { DIStateControl } from 'di-controls';
        ╵                                ~~~~~~~~~~~~~


X [ERROR] TS2307: Cannot find module '@tinkoff/ng-polymorpheus' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@ng-doc/ui-kit/components/overlay-container/overlay-container.component.d.ts:6:44:
      6 │ ...rt { PolymorpheusOutletDirective } from '@tinkoff/ng-polymorpheus';
        ╵                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~


X [ERROR] TS2307: Cannot find module 'di-controls' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@ng-doc/ui-kit/components/toggle/toggle.component.d.ts:3:31:
      3 │ import { DIStateControl } from 'di-controls';
        ╵                                ~~~~~~~~~~~~~


X [ERROR] TS2420: Class 'NgDocToggleComponent<T>' incorrectly implements interface 'ControlValueAccessor'.
  Type 'NgDocToggleComponent<T>' is missing the following properties from type 'ControlValueAccessor': writeValue, registerOnChange, registerOnTouched [plugin angular-compiler]

    node_modules/@ng-doc/ui-kit/components/toggle/toggle.component.d.ts:5:21:
      5 │ export declare class NgDocToggleComponent<T> extends DIStateControl...
        ╵                      ~~~~~~~~~~~~~~~~~~~~


X [ERROR] TS2307: Cannot find module '@tinkoff/ng-polymorpheus' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@ng-doc/ui-kit/types/content.d.ts:2:81:
      2 │ ...eusHandler, PolymorpheusTemplate } from '@tinkoff/ng-polymorpheus';
```
```


### OS

Windows

### Browser

Chrome

### Node version

20.9.0

### Anything else?

_No response_

**Comment by skoropadas** [comment]
Hi thanks for the issue! Looks like some packages were not installed, I'll fix it tomorrow!

**Comment by skoropadas** [comment]
I have fixed several issues with the automatic package installation caused by the latest update. However, I couldn't reproduce this particular issue. I suspect that, for some reason, the `peerDependencies` of the packages were not installed on your end. Please try deleting `node_modules` and `package-lock.json`, and then reinstall all packages, including the latest version of NgDoc (17.1.2).

Also, ensure that you are using the latest version of Angular, including the latest patch version of `@angular-devkit/build-angular` (the Angular team renamed one of the builder methods, so NgDoc won't work on version 17.0.0 but will work on version 17.0.2).

**Comment by dhutaryan** [comment]
I had `@angular-devkit/build-angular` v17.0.0. Anyway, I updated all versions and install it again. Unfortunately, it didn't help.
One more thing which I forgot to say before. I have library and demo app with documentation. Demo app import styles from library and it doesn't work as well.

```
X [ERROR] Can't find stylesheet to import.
  ╷
5 │ @use "projects/mat-timepicker" as mat-timepicker;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  projects\demo-app\src\styles.scss 5:1  root stylesheet [plugin angular-sass]

    angular:styles/global:styles:2:8:
      2 │ @import 'projects/demo-app/src/styles.scss';
```

I had some warnings while installing dependencies
```
warning " > @ng-doc/app@17.1.2" has unmet peer dependency "@ng-web-apis/common@2.0.1".
warning " > @ng-doc/app@17.1.2" has unmet peer dependency "di-controls@2.1.0".
warning " > @ng-doc/ui-kit@17.1.2" has unmet peer dependency "@ngneat/until-destroy@9.2.0".
warning " > @ng-doc/ui-kit@17.1.2" has unmet peer dependency "di-controls@2.1.0".
warning " > @ng-doc/ui-kit@17.1.2" has unmet peer dependency "@tinkoff/ng-polymorpheus@4.0.11".
warning "@ng-doc/builder > ng-morph@4.0.3" has unmet peer dependency "@angular-devkit/core@>=11.0.0".
warning "@ng-doc/builder > ng-morph@4.0.3" has unmet peer dependency "@angular-devkit/schematics@>=11.0.0".
```

package.json dependencies
```
  "dependencies": {
    "@angular/animations": "^17.0.2",
    "@angular/cdk": "^17.0.1",
    "@angular/common": "^17.0.2",
    "@angular/compiler": "^17.0.2",
    "@angular/core": "^17.0.2",
    "@angular/flex-layout": "^15.0.0-beta.42",
    "@angular/forms": "^17.0.2",
    "@angular/material": "^17.0.1",
    "@angular/platform-browser": "^17.0.2",
    "@angular/platform-browser-dynamic": "^17.0.2",
    "@angular/router": "^17.0.2",
    "@ng-doc/app": "^17.1.2",
    "@ng-doc/builder": "^17.1.2",
    "@ng-doc/core": "^17.1.2",
    "@ng-doc/ui-kit": "^17.1.2",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^17.0.2",
    "@angular/cli": "^17.0.2",
    "@angular/compiler-cli": "^17.0.2",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~4.0.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "ng-packagr": "^17.0.0",
    "typescript": "5.2.2"
  }
```

**Comment by skoropadas** [comment]
@dhutaryan as I understand your project is open source can I have a branch to test these errors? because it's quite difficult to say what goes wrong. I can't reproduce it on a clear project or on existing ones.

**Comment by dhutaryan** [comment]
I think you can fork it and add `ng-doc` for demo app. Here is the link https://github.com/dhutaryan/ngx-mat-timepicker

**Comment by skoropadas** [comment]
@dhutaryan great, thank you! I'll check it today!

**Comment by skoropadas** [comment]
@dhutaryan I looked at the repository, and here's what I found:

The `@angular/cdk` and `@angular/material` packages were not updated in the `master` branch. I updated all packages, fixing all issues, and obtained the following `package.json`.

<details>
  <summary>👉 package.json</summary>
  
  ```json
{
  "name": "ngx-mat-timepicker",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --configuration production --base-href=/ngx-mat-timepicker/",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "build:lib": "ng build mat-timepicker --configuration production",
    "test:lib": "ng test mat-timepicker --code-coverage"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^17.0.4",
    "@angular/cdk": "^17.0.1",
    "@angular/common": "^17.0.4",
    "@angular/compiler": "^17.0.4",
    "@angular/core": "^17.0.4",
    "@angular/flex-layout": "^15.0.0-beta.42",
    "@angular/forms": "^17.0.4",
    "@angular/material": "^17.0.1",
    "@angular/platform-browser": "^17.0.4",
    "@angular/platform-browser-dynamic": "^17.0.4",
    "@angular/router": "^17.0.4",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^17.0.2",
    "@angular/cli": "^17.0.2",
    "@angular/compiler-cli": "^17.0.4",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~4.0.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "ng-packagr": "^17.0.0",
    "typescript": "5.2.2"
  }
}

  ```
  
</details>

Next, I installed NgDoc using the command `ng add @ng-doc/add`. The migrations were successful, but I noticed that the application was not created with Angular 17, so not everything worked right away. The issue is that in NgDoc version 17, all migrations were updated to support Angular version 17, so your `angular.json` wasn't migrated. There are a few possible solutions:

1. You could install NgDoc version 16.7 first and then migrate to NgDoc version 17 using `ng update @ng-doc/builder`. However, I think this might cause more problems with package installation since your project is already on Angular version 17.

2. You can use the updated `angular.json` below, in which I made all the necessary fixes:

<details>
  <summary>👉 angular.json</summary>

  ```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "cli": {
    "packageManager": "yarn"
  },
  "newProjectRoot": "projects",
  "projects": {
    "demo-app": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss",
          "changeDetection": "OnPush"
        },
        "@schematics/angular:application": {
          "strict": true
        }
      },
      "root": "",
      "sourceRoot": "projects/demo-app/src",
      "prefix": "demo",
      "architect": {
        "build": {
          "builder": "@ng-doc/builder:application",
          "options": {
            "outputPath": "dist/demo-app",
            "index": "projects/demo-app/src/index.html",
            "browser": "projects/demo-app/src/main.ts",
            "polyfills": ["projects/demo-app/src/polyfills.ts"],
            "tsConfig": "projects/demo-app/tsconfig.app.json",
            "inlineStyleLanguage": "scss",
            "stylePreprocessorOptions": {
              "includePaths": [""]
            },
            "assets": [
              {
                "glob": "**/*",
                "input": "node_modules/@ng-doc/app/assets",
                "output": "assets/ng-doc/app"
              },
              {
                "glob": "**/*",
                "input": "node_modules/@ng-doc/ui-kit/assets",
                "output": "assets/ng-doc/ui-kit"
              },
              {
                "glob": "**/*",
                "input": "ng-doc/demo-app/assets",
                "output": "assets/ng-doc"
              },
              "projects/demo-app/src/favicon.ico",
              "projects/demo-app/src/assets"
            ],
            "styles": [
              "node_modules/@ng-doc/app/styles/global.css",
              "projects/demo-app/src/styles.scss"
            ],
            "scripts": [],
            "allowedCommonJsDependencies": [
              "@ng-doc/core"
            ]
          },
          "configurations": {
            "production": {
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "500kb",
                  "maximumError": "1mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "2kb",
                  "maximumError": "4kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "projects/demo-app/src/environments/environment.ts",
                  "with": "projects/demo-app/src/environments/environment.prod.ts"
                }
              ],
              "outputHashing": "all"
            },
            "development": {
              "optimization": false,
              "extractLicenses": false,
              "sourceMap": true,
              "namedChunks": true
            }
          },
          "defaultConfiguration": "production"
        },
        "serve": {
          "builder": "@ng-doc/builder:dev-server",
          "configurations": {
            "production": {
              "buildTarget": "demo-app:build:production"
            },
            "development": {
              "buildTarget": "demo-app:build:development"
            }
          },
          "defaultConfiguration": "development"
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "buildTarget": "demo-app:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "projects/demo-app/src/test.ts",
            "polyfills": "projects/demo-app/src/polyfills.ts",
            "tsConfig": "projects/demo-app/tsconfig.spec.json",
            "karmaConfig": "projects/demo-app/karma.conf.js",
            "inlineStyleLanguage": "scss",
            "assets": [
              "projects/demo-app/src/favicon.ico",
              "projects/demo-app/src/assets"
            ],
            "styles": [
              "projects/demo-app/src/styles.scss"
            ],
            "scripts": []
          }
        }
      }
    },
    "mat-timepicker": {
      "projectType": "library",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss",
          "changeDetection": "OnPush"
        }
      },
      "root": "projects/mat-timepicker",
      "sourceRoot": "projects/mat-timepicker/src",
      "prefix": "mat",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:ng-packagr",
          "options": {
            "project": "projects/mat-timepicker/ng-package.json"
          },
          "configurations": {
            "production": {
              "tsConfig": "projects/mat-timepicker/tsconfig.lib.prod.json"
            },
            "development": {
              "tsConfig": "projects/mat-timepicker/tsconfig.lib.json"
            }
          },
          "defaultConfiguration": "production"
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "projects/mat-timepicker/src/test.ts",
            "tsConfig": "projects/mat-timepicker/tsconfig.spec.json",
            "karmaConfig": "projects/mat-timepicker/karma.conf.js"
          }
        }
      }
    }
  }
}

  ```
</details>


### Regarding styles
The issue with importing `@use "projects/mat-timepicker" as mat-timepicker;` can be resolved by adding additional configuration to `angular.json`:

```json
"stylePreprocessorOptions": {
   "includePaths": [""]
},
```

I've already added it to the `angular.json` code above. Pls tell me if it works for you.

**Comment by dhutaryan** [comment]
I've solved it. I was thinking about these warnings
```
warning " > @ng-doc/app@17.1.2" has unmet peer dependency "@ng-web-apis/common@2.0.1".
warning " > @ng-doc/app@17.1.2" has unmet peer dependency "di-controls@2.1.0".
warning " > @ng-doc/ui-kit@17.1.2" has unmet peer dependency "@ngneat/until-destroy@9.2.0".
warning " > @ng-doc/ui-kit@17.1.2" has unmet peer dependency "di-controls@2.1.0".
warning " > @ng-doc/ui-kit@17.1.2" has unmet peer dependency "@tinkoff/ng-polymorpheus@4.0.11".
```
Because I felt something wrong here and I was right. `has unmet peer dependency` means I have to install these dependencies manually by myself. I reckon we so used to not doing it that I didn't expect that.
Installation page says nothing about it 😄 Probably it would be nice to bump versions in this case or use `>=`

Thank you for your work and quickly responses. I'm really appreciated it 👍

**Comment by skoropadas** [comment]
Well, all of these packages are `peerDependencies` of NgDoc, I saw that you are using `yarn` but I'm not sure how it works with it, but it works fine with `npm`. Anyways if the problem is solved then I'll close the issue :)

**Comment by dhutaryan** [comment]
You are right. I did an experiment. I created 2 new projects (with `npm` and `yarn`) with the latest angular version. Everything works good with `npm` unlike `yarn`. It happens because npm@7 or more installs all peer dependencies automatically. Yarn team disagree with that approach and won't implement it (https://github.com/yarnpkg/berry/issues/3710). Another issue https://github.com/yarnpkg/berry/issues/5421

After some research I found a few solutions for that:

- install all peer dependencies manually 
The easiest solution. But if you use the same libraries you have to keep compatible versions.

- use `yarnrc.yml` file
This works for `yarn` v4. Put the following code to `yarnrc.yml`
```
packageExtensions:
  "@ng-doc/app@*":
    dependencies:
      "@ng-web-apis/common": "*"
      "di-controls": "*"
  "@ng-doc/ui-kit@*":
    dependencies:
      "@ngneat/until-destroy": "*"
      "@tinkoff/ng-polymorpheus": "4.0.11" // this important because a newer version have another types
      "di-controls": "*"
```

@skoropadas don't you think to put packages into dependencies. First of all it will help people who use `yarn`, like me 😄 There is a technical explanation. Usually peer dependencies include package which you might not use in the project but you need it (hi babel) or their usage is not obvious. As I see `ng-doc` uses all these packages directly. So, it depends on them.
